title: ergulburak
author: GitHub User
email: burakcan41@gmail.com
description: > # this means to ignore newlines until "show_exerpts:"
  Merhaba, ben Burak. Bilgisayar Mühendisliği son sınıf öğrencisiyim. 
  Amatör olarak 4 yıldır oyun geliştirme ile ilgileniyorum. Burada oyun 
  geliştirme ve mobil uygulama hakkında öğretici içerikler paylaşmayı düşünüyorum.
show_excerpts: false # set to true to show excerpts on the homepage

paginate: 5
paginate_path: "/blog/page:num/"

tag_permalink_style: pretty
tag_page_layout: tag_page
tag_page_dir: tag

# jekyll-dash date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
dash:
  date_format: "%b %-d, %Y"

  disqus:
    shortname: ergulburak-github-io

  # generate social links in footer
  # supported colors: green, red, orange, blue, cyan, pink, teal, yellow, indigo, purple
  social_links:
    - url: https://twitter.com/BurakERGUL_
      icon: twitter-square
      color: cyan
    - url: https://lugreb.itch.io
      icon: itch-io
      color: red
    - url: https://github.com/ergulburak
      icon: github-square
      color: purple
    - url: https://www.youtube.com/channel/UCsPgp8dgYeAL8ar4BAOFEEg
      icon: youtube
      color: red
    - url: https://www.linkedin.com/in/lugreb/
      icon: linkedin
      color: blue
    - url: https://www.instagram.com/burake41/
      icon: instagram
      color: orange

  show_author: true

  animation_speed: 50

google_analytics: G-3DWR3NTPNX
# Build settings
theme: jekyll-dash

plugins:
 - jekyll-feed
 - jekyll-seo-tag
 - jekyll-paginate
 - liquid-md5
 - jekyll/tagging

# Replaces the default avatar provider (gravatar)
avatar_source: github
github_username: ergulburak
